apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: hubb-app
spec:
  selector:
    matchLabels:
      app: hubb-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hubb-app
    spec:
      containers:
      - image: hubbdevelopers/hubb_test:latest
        name: hubb-app
        env:
        - name: GOPATH
          value: /go
        - name: GIN_MODE
          value: debug
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_USER
          value: test
        - name: MYSQL_PASSWORD
          value: test
        - name: MYSQL_DATABASE
          value: test
        - name: MYSQL_HOST
          value: mysql
        ports:
        - containerPort: 8080
          name: hubb-app
      imagePullSecrets:
        - name: regcred